<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Nullable>enable</Nullable>
    
    <DefaultItemExcludes>$(DefaultItemExcludes);V3\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="D:\Projects\Carrot.Memory\Carrot.Memory\Carrot.Memory.csproj" />
    <PackageReference Include="Parquet.Net" Version="6.0.3" />
    <PackageReference Include="Sylvan.Data.Csv" Version="1.4.4" />
  </ItemGroup>

</Project>
