<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>4.0.0.0-dev</AssemblyVersion>
   </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carrot.Memory" Version="1.0.0" />
  </ItemGroup>

</Project>
