name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE: CarrotQuant.NET.sln

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore $env:SOLUTION_FILE
    - name: Build
      run: dotnet build $env:SOLUTION_FILE --no-restore
    - name: Test
      run: dotnet test $env:SOLUTION_FILE --no-build --verbosity normal
